### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jakealistairwood** [jjgray90/oxna-portfolio#5]
Hey JJ, 

This is super work!! Smashed it!! I've added some feedback but there really isn't too much to add:

What you did well:
- Good use of Modifiers
- SCSS is really well nested 
- Used responsive units throughout which is great to see
- Loving the use of mixins
- Great job of splitting your SCSS into partial files
- Fully responsive
- Looking really close to the original Figma wireframe so great attention-to-detail there

How it could be improved: 
- Clean up your folder structure slightly, I'd recommend doing the following:
```
assets/
    icons/
    images/
    scss/
        // any scss file in here
```

**Comment by jjgray90** [comment]
Thanks for the feedback Jake! I've restructured the files as you've suggested.
